src/Entity/Plainte.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlainteRepository")
 */
class Plainte
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $agent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Motif;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAgent(): ?string
    {
        return $this->agent;
    }

    public function setAgent(string $agent): self
    {
        $this->agent = $agent;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->Motif;
    }

    public function setMotif(string $Motif): self
    {
        $this->Motif = $Motif;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\PhoneCalls;
use App\Form\UserInGameType;

use App\Entity\GestionJoueurs;

use App\Entity\CasierJudicaire;


use App\Entity\VehiculesJoueurs;
use App\Repository\UserRepository;
use App\Repository\PhoneCallsRepository;
use App\Repository\GestionJoueursRepository;
use App\Repository\CasierJudicaireRepository;
use App\Repository\TelephoneAppelsRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\VehiculesJoueursRepository;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProfilController extends AbstractController
{
    /**
     * @Route("/membre", name="member_profil")
     */
    public function index(UserRepository $repo, CasierJudicaireRepository $repoC, GestionJoueursRepository $repoG, PhoneCallsRepository $repoA, VehiculesJoueursRepository $repoV)
    {
        $id = $this->getUser()->getId();
        $steam = $this->getUser()->getSteamHex();
        $user = $this->getUser()->getUsername();
        $role = $this->getUser()->getRoles();
        

     

        $account = new User();
        $account = $repo->findBy(array('id' => $id));

      

       
        $joueur = new GestionJoueurs();
        $joueur = $repoG->findBy(array('identifier' => $steam));
        if(!empty($joueur)){
            $joueur = $joueur[0];
        }
        else{
            $joueur = [];
        }


        if(isset($joueur) and !empty($joueur)){
            $casier = new CasierJudicaire();
            $casier = $repoC->findBy(array('telephone' => $joueur->getTelephone()));
        }
        else{
            $casier = [];
        }
        


        if(isset($joueur) and !empty($joueur)){
        $appel = new PhoneCalls();
        $appel = $repoA->findBy(array('owner' => $joueur->getTelephone()));
        }
        else{
            $appel = [];
        }

        $veh = new VehiculesJoueurs();
        $veh = $repoV->findBy(array('identifier' => $steam));
        
      
     dump($casier);

        return $this->render('profil/index.html.twig', [
            'account' => $account,
            'joueur' => $joueur,
            'roles' => $role,
            'username' => $user,
            'phoneCalls' => $appel,
            'vehicules' => $veh,
            'casier' => $casier,
        ]);
    }

    
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil de {{ username }}{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="#"><img src="{{ asset('images/logo.jpg')}}" style="max-width: 50px; max-height: 50px;"></a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{{ path('index')}}"><button class="btn btn-primary btnPerso" >Retour à l'accueil</button></a>
    </li>
   {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_MODO')%}
                                                  
    <li class="nav-item">
      <a href="../admin" class="nav-link"><button class="btn btn-succees btnPerso">Admin</button></a>
    </li>
    {% endif %}
  </ul>

</nav>
 {% include 'includes/menuProfile.html.twig' %}

 <div class="jumbotron">
  <h1>Bienvenue {{ username }} sur ta page de profil</h1>
  <p>En cas de problème avec ton compte merci de contacter un membre de l'équipe de Reborn RP</p>
</div>

<div class="row">
  <div class="col-lg-4 col-md-5 col-sm-12 profilBox">
  {% if  joueurs is not defined %}
<div class="col-lg-4 col-md-5 col-sm-12 profilBox"> Aucun Profil In-Game </div>
  {% else %}
  {% for joueurs in joueur %}
  
      <div class="card">
      <div class="card-header"> <h3>Information Joueur</h3></div>
          <div class="card-body">
          
          <b>Nom du personnage</b> {{ joueurs.nom }} 
              <b>Prénom du personnage</b> {{ joueurs.prenom }} 
              <b>Date de naissance : </b> {{ joueurs.dateNaissance|date('d/m/Y') }} 
              <b>Argent en poche</b> {{ joueurs.argent }} <br/>
              <b>Argent en banque</b> {{ joueurs.banque }} <br/>
              <b>Numéro de téléphone </b> {{ joueurs.telephone }} 
             
          </div>
      <div class="card-footer">
      
              <div class="progress">
                <div class="progress-bar bg-danger" style="padding: 5px; width:{{ joueurs.sante }}%; max-width: 200%;">Santer : {{ joueurs.sante }}/200%</div>
              </div>

            
            <div class="progress">
              <div class="progress-bar bg-info" style="padding: 5px; width:{{ joueurs.pain }}%; max-width: 100%;">Fain : {{ joueurs.pain }}/100%</div>
            </div>

            <div class="progress">
              <div class="progress-bar bg-warning" style="padding: 5px; color: #333 !important; width:{{ joueurs.eau }}%; max-width: 100%;">Soif : {{ joueurs.eau }}/100%</div>
            </div>

            <div class="progress">
              <div class="progress-bar bg-warning" style=" background-color: purple !important; width:{{ joueurs.alcool }}%; max-width: 100%;">Alcooliser : {{ joueurs.alcool }}/100%</div>
            </div>
          
      
      </div>
</div>
      {# <b>Id Steam du Compte</b> {{ joueur.identifier }} #}
    {% endfor %}
    {% endif %}
  </div>

<div class="col-lg-4 col-md-4 col-sm-12 profilBoxC">
   <div class="card">
      <div class="card-header"> <h3>Casier Judicaire</h3></div>
    {% if  joueurs is defined and casier is defined %}
      {% for casiers in casier %}
       {% if not casiers.telephone %}
          <div class="card-body"><span class="badge badge-success">Inconnue des services de police</span></div>
        {% else %}
        <div class="card-body"><span class="badge badge-danger">Connue des service de police </span><div class="spinner-grow text-danger"></div></div>
        <div class="card-footer"><a href="{{ path('user_casier_view',{'id': casiers.id })}}"><button class="btn btn-warning" style="width:100%;">Voir</button></a></div>
        {% endif %}
      {% endfor %}
     {% if casier is not defined %}
     {% else %}
       <div class="card-body"><span class="badge badge-success">Inconnue des services de police</span></div>
     {% endif %}
    {% endif %}
  </div>
  
</div>



{#  Véhicule joueur   #}
<div class="boxVehicule">
{% if vehicule is not defined %}
<div class="card" style="">
Aucun Véhicule
</div>
{% else %}
  {% for vehicule in vehicules %}
        <div class="col-lg-4 col-md-4 col-sm-12 card" style="max-width: 270px; padding: 10px; text-align:center; font-size: 10px !important;">
              <img class="card-img-top" style="margin-left: 10%; border-radius: 10px;max-width:200px; max-height: 200px; "src="images/img_cars/{{ vehicule.vehicleModel }}.png" alt="{{ vehicule.vehicleName }}">
              <div class="card-body">
                <h4 class="card-title">{{ vehicule.vehicleName }}</h4>
                <p class="card-text">
                Plaque du Véhicule : <strong style="color: red;">{{ vehicule.vehiclePlate }}</strong><br/>
                Véhicule en Fourriere ? : {% if vehicule.vehicleFourriere == "Oui" %}
                <span class="badge badge-info">OUI</span>
                {% else %}
                <span class="badge badge-info">NON</span>
                {% endif %}<br/>

                 Véhicule au garage ? : {% if vehicule.vehicleState == "Sorti" %}
                <span class="badge badge-danger">NON</span>
                {% else %}
                <span class="badge badge-success">Oui</span>
                {% endif %}<br/>

                 Véhicule Voler ? : {% if vehicule.vehicleVoler == "Oui" %}
                <span class="badge badge-danger">OUI</span>
                {% else %}
                <span class="badge badge-success">Non</span>
                {% endif %}<br/>
                </p>
                
              </div>
          
        </div>
        {% endfor %}
{% endif %}
</div>
{% endblock %}